name: AuroraParticles
version: '${project.version}'
main: io.github.aaronr92.auroraproject.Plugin
api-version: 1.19
authors: [ AaronR92 ]
commands:
  particle:
    usage: "/particle"
    description: "Creates particle"